parameters:
  mailer.gmail_user: 'magali@gmail.com'
  mailer.gmail_password: 'password'

services:
  _instanceof:
    App\HasLoggerInterface:
      public: true
      autowire: true
      tags: ['with_logger']
  _defaults:
    autowire: true
    public: true
  order_controller:
    class: App\Controller\OrderController
    calls:
      - [sayHello, ['bonyour', 'jean']]
      - [setSecondaryMailer, ['@mailer.gmail']]
  texter.sms:
    class: App\Texter\SmsTexter
    arguments: [ 'service.sms.com', 'apikey1234']
  App\Controller\OrderController:
    alias: order_controller
    public: true
  App\Database\Database: '@database'
  App\\Mailer\GmailMailer: '@mailer.gmail'
  App\texter\SmsTexter: '@texter.sms'
  App\Mailer\SmtpMailer: '@mailer.smtp'
  App\Mailer\MailerInterface: '@mailer.smtp'
  App\Texter\FaxTexter: '@texter.fax'
  App\Texter\TexterInterface: '@texter.sms'
  App\Logger: '@logger'